[workspace]
members = ["apps/dioxus-web-app"]
exclude = [
  "target/", # exclude bench testing
  ".moon/",
  "packages/"
]
resolver = "2"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
