services:
  waku:
    build:
      context: .
      dockerfile: ./apps/waku-project/Dockerfile
    container_name: waku
    restart: unless-stopped
    environment:
      NODE_ENV: production
    tty: true
    # ports:
    #   - 8080:8080
  
  next:
    build:
      context: .
      dockerfile: ./apps/next-fifteen/Dockerfile
    container_name: next
    restart: unless-stopped
    environment:
      NODE_ENV: production
    # tty: true
    ports:
      - 8081:8080
